# permissions for end users to edit parseables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: parseable-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: parseable-operator
    app.kubernetes.io/part-of: parseable-operator
    app.kubernetes.io/managed-by: kustomize
  name: parseable-editor-role
rules:
- apiGroups:
  - parseable.io.parseable.io
  resources:
  - parseables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - parseable.io.parseable.io
  resources:
  - parseables/status
  verbs:
  - get
