apiVersion: parseable.io/v1beta1
kind: ParseableTenant
metadata:
  name: parseable
spec:
  nodes:
    - name: server
      kind: Deployment
      replicas: 1
      nodeType: server
      k8sConfigGroup: k8s-server
      parseableConfigGroup: server-config
  deploymentOrder:
  - server
  external:
    objectStore:
      spec:
        type: s3
        data: |-
          s3.url=http://minio.minio.svc.cluster.local:9000
          s3.access.key=minioadmin
          s3 .secret.key=minioadmin
          s3.region=us-east-1
          s3.bucket=parseable
  k8sConfigGroup:
  - name: k8s-server
    spec:
      volumes:
      - name: pvctest
        persistentVolumeClaim:
          claimName: pvctest
      containers:
      - command:
          - sleep
          - "3600"
        image: praqma/network-multitool
        name: debug-network-container
        volumeMounts:
        # a mount for site-data
        - name: pvctest
          mountPath: /data
    storageConfig:
    - name: pvctest
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: "civo-volume"
        resources:
          requests:
            storage: 10Gi
  parseableConfigGroup:
  - name: server-config
    data: |-
      addr=0.0.0.0:8000 
      staging.dir=./staging
      fs.dir=./data
      username=admin
      password=admin
