apiVersion: parseable.io/v1beta1
kind: ParseableTenant
metadata:
  name: parseable
spec:
  nodes:
    - name: parseable-server1
      kind: Statefulset
      replicas: 1
      nodeType: server
      k8sConfigGroup: parseableserver
      parseableConfigGroup: parseableserver
    - name: parseable-ingestor
      kind: Statefulset
      replicas: 1
      nodeType: ingestor
      k8sConfigGroup: parseableserver
      parseableConfigGroup: parseable-ongestr
    - name: parseable-server
      kind: Statefulset
      replicas: 1
      nodeType: server
      k8sConfigGroup: parseableserver
      parseableConfigGroup: parseableserver
  deploymentOrder:
  - server
  external:
    objectStore:
      spec:
        type: s3
        data: |-
          s3.url=http://minio.minio.svc.cluster.local:9000
          s3.access.key=minioadmin
          s3 .secret.key=minioadmin
          s3.region=us-east-1
          s3.bucket=parseable
  k8sConfigGroup:
  - name: parseable-server
    spec:
      serviceAccountName: "parsebale-server"
      nodeSelector: {}
      tolerations: []
      affinity: {}
      containers: []
  parseableConfigGroup:
  - name: parseableserver
    data: |-
      addr=0.0.0.0:8000 
      staging.dir=./staging
      fs.dir=./data
      username=admin
      password=admin
  - name: parseable-ongestr
    data: |-
      addr=0.0.0.0:8000 
      staging.dir=./staging
      fs.dir=./data
      username=admin
      password=admin 
